#+CATEGORY: proyecto, curro, medialab-prado
#+TAGS: transparencia, participación ciudadana, open data, datos abiertos
#+DESCRIPTION: Agenda del proyecto de Transparencia y participación ciudadana de Medialab-Prado
#+TITLE: Visualizar'17: Migraciones, convocatoria de proyectos
#+DATE: <2017-04-27 jue>
#+AUTHOR: Adolfo Antón Bravo
#+EMAIL: adolfo@medialab-prado.es
#+OPTIONS: todo:nil pri:nil tags:nil ^:nil 

#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:nil reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+OPTIONS: toc:nil
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: linear
#+REVEAL_THEME: sky
#+REVEAL_HLEVEL: 2
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal Introduction.">
#+REVEAL_POSTAMBLE: <p> Creado por adolflow. </p>
#+REVEAL_PLUGINS: (highlight markdown notes)
#+REVEAL_EXTRA_CSS: file:///home/flow/Documentos/software/reveal.js/css/reveal.css
#+REVEAL_ROOT: file:///home/flow/Documentos/software/reveal.js/

Would you like to apply for the /Visualizar'17: Migrations/ call for
projects?  Fill out the form before June 18. During the workshop we will
celebrate from 15 to 30 September, there will be developed simultaneously a
maximum of 8 proposals selected from this open call for ideas or projects.

#+CAPTION: Migration, por ashokboghani, CC BY NC 2.0
#+ATTR_HTML: :alt Migration, por ashokboghani, CC BY NC 2.0 :title v17
http://medialab-prado.es/mmedia/20/20249/500_0.jpg

The proposals submitted must necessarily be open to the pParticipation
of collaborators or interested parties who can contribute to their
development during the workshop.

Las propuestas presentadas deberán estar necesariamente abiertas a la
participación de colaboradorxs interesadxs que puedan contribuir a su
desarrollo durante el taller.

Las propuestas podrán presentarse de forma individual o
colectiva. Cada participante o equipo podrá presentar tantas
propuestas como desee.

* Inscripción

En esta edición te animamos a que nos envíes la propuesta y también a
que publiques el proyecto en alguna URL, por ejemplo en Github, para
que no solo nosotrxs evaluemos el proyecto, sino que también lxs
potenciales colaboradorxs podrán empezar a participar en el proyecto.

Recordamos las fechas:
- Convocatoria de proyectos: 4 de mayo a 15 de junio.
- Fallo de proyectos seleccionados: 22 de junio.
- Convocatoria de colaboradorxs: 22 de junio a 1 de septiembre.

* Indicaciones para el envío de las propuestas

El resumen del proyecto deberá presentarse en castellano y en
inglés. Si no te cabe la versión en inglés en el campo =resumen del
proyecto=, inclúyela por favor en el campo =descripción de tu
proyecto=. Si no hablas castellano, puedes presentarla únicamente en
inglés.

Con el fin de facilitar la participación de colaboradorxs en tu
proyecto, sería de gran ayuda que adjuntaras un sencillo y muy breve
vídeo (2/3 min) explicándolo.


* Compromisos de los seleccionados

Las personas o colectivos seleccionados se comprometen a:
- Asistir todos los días del taller.
- La finalización y adecuada documentación de los proyectos
  propuestos.
- Aceptar y fomentar la participación de
  las personas interesadas.
- Aportar información básica de los proyectos, tanto del proceso, como de
  los resultados, deberá ser registrada en el repositorio de Github
  que creemos para la ocasión en el [[https://github.com/medialabprado][Github de Medialab-Prado]].
- Mantener los materiales del proyecto en el repositorio ofrecido con
  licencias libres que permitan la reutilización o adaptación del
- Incluir en los créditos del proyecto la participación de cada
  miembrx del equipo y su desarrollo en el marco del taller.

* Notas

- La organización apoyará en la consecución de todos los compromisos anteriores.
- La organización anima y apoya la utilización de programas libres
  para el desarrollo de los proyectos.
- Los proyectos realizados serán exhibidos públicamente en
  Medialab-Prado. Una vez finalizada la exhibición, los participantes
  se comprometen a retirar sus materiales en el plazo máximo de 15
  días. Pasado dicho plazo, Medialab-Prado se reserva derecho a hacer
  con ellos lo que estime conveniente.

* Resolución. Criterios para la valoración de los proyectos
** Comité de selección
El equipo organizador de /Visualizar’17 Migraciones/ de Medialab-Prado junto con
el equipo de coordinación del taller y lxs mentorxs valorarán los
proyectos enviados.
** Criterios de evaluación

- Relevancia para los objetivos generales y la temática de la
  convocatoria.
- Calidad del proyecto.
- Originalidad, carácter innovador o experimental.
- Claridad de la propuesta y adecuación a la metodología y el tiempo
  de desarrollo del taller. El objetivo es tener un prototipo al final
  del  taller. Por tanto, en caso de que forme parte de un proyecto
  con otras fases, en la propuesta deberán especificarse las partes
  del proyecto que podrían ser prototipadas en este periodo de tiempo
  y las que no.
- Concurrencia de una variedad de campos de conocimiento.
- Uso de herramientas y licencias libres.
- Que sea beneficioso para la comunidad.
- Se valorará la diversidad de aproximaciones y procedencias, y su
  integración en el conjunto de las propuestas a seleccionar.

* Alojamiento y viajes
Previa solicitud y para aquellos participantes que residan fuera de
Madrid, Medialab-Prado proporcionará alojamiento durante el tiempo de
desarrollo del taller.

También se cubrirán los gastos de desplazamiento de una persona por
cada uno de los proyectos seleccionados.

* Idioma del taller

El taller se desarrollará en inglés y en castellano sin traducción
formal, dependiendo de la nacionalidad o idioma hablado de lxs
participantes en el taller.

* Difusión y continuidad de los proyectos

Los trabajos desarrollados serán presentados públicamente por los
equipos de trabajo en la jornada final del taller, el 30 de septiembre.

Tras la finalización del taller se organizará una exposición que se
difundirá y quedará abierta al público en Medialab-Prado.

La información básica de los proyectos, tanto del proceso, como de los
resultados, deberá ser registrada dentro del espacio de [[https://github.com/medialab-prado/][Medialab-Prado
en Github]] que se ofrezca al proyecto.

* Entidades colaboradoras

Esta convocatoria es también una invitación a organizaciones que
trabajen con los datos como materia prima fundamental de su
actividad en la temática propuesta.

Invitamos a estas organizaciones a ofrecer conjuntos de datos y a
proponer retos para su desarrollo. Durante la convocatoria de
proyectos se irán sumando las propuestas.

* Contacto

- visualizar [arroba] medialab-prado.es
- [[https://twitter.com/datalabx][@datalabx]] en Twitter.
- [[https://github.com/flowsta][@flowsta]] en GitHub.

* Autoría y propiedad intelectual

La actividad será grabada en formato vídeo con audio y difundida a
través de la web de Medialab-Prado (MLP). La participación en la
actividad supondrá autorizar a MLP fijar, reproducir, distribuir y
comunicar públicamente el derecho de imagen de los participantes y
asistentes, pudiendo el vídeo y audio grabado ser difundido entre el
público en general por cualquier medio y, en especial, por Internet,
cediendo el derecho de transformación con el objeto de adaptar la obra
al soporte en el que se fijare o su conservación.

Si el vídeo y el audio se comunicaran públicamente de forma parcial,
se hará por parte de MLP todo lo posible para no desnaturalizar el
contenido grabado. El acceso en que MLP facilite al público en general
al material grabado se hará sin mediar contraprestación económica
alguna por el mismo.

La obra se difundirá con una licencia de uso que permita a cualquier
usuario su libre reproducción y difusión por cualquier medio. MLP
incluirá junto a la misma un enlace a la licencia referida a fin de
que el usuario pueda conocer los términos de la misma. Esta cesión se
entenderá realizada por el tiempo máximo permitido legalmente y con
ámbito territorial de todo el mundo.

Los autores de conferencias deberán expresamente firmar su
autorización para la utilización por parte de MLP de sus derechos de
imagen así como para la cesión de la propiedad intelectual de la
conferencia en concordancia con los fines de la institución de
difusión de la cultura libre.

Para poder concurrir a esta actividad, el participante siempre que sus
textos, fotografías o vídeos (las obras) enviados a MLP hayan sido
aceptados, deberá licenciar las obras con una licencia en la que se le
permita a MLP la publicación de las mismas en cualquier formato físico
o digital con los alcances territorial y temporal máximos señalados en
la ley, permitiendo su transformación para la mejor difusión o
distribución de las obras. Una vez seleccionadas las obras y dentro
del transcurso de la actividad, el autor está obligado a  permitir que
cualesquiera otros participantes de la actividad convocada puedan
tomar su obra como base para realizar otras obras derivadas.

Asimismo, el participante deberá mantener su código en un repositorio
de acceso público (por ejemplo Github.com) y tener el mismo licenciado
bajo una licencia libre que permita la reutilización del mismo.

Los materiales aportados por MLP permanecerán propiedad de esta
institución incluso aunque se hubieran mezclado de manera inseparable
con los materiales aportados por el participante. Los participantes
deberán retirar los objetos aportados y no utilizados en el plazo
máximo de 15 días desde la finalización de la actividad. Pasado dicho
plazo, MLP se reserva el derecho a destinar los bienes conforme su
unilateral criterio.

La participación en la presente convocatoria supone la aceptación de
todas sus bases y contenidos de la misma.

* Proyectos inspiradores

Los ejemplos siguientes pueden servir como inspiración o sugerencia a la hora de presentar proyectos:
- [[http://comunidad.medialab-prado.es/en/search/content/visualizar][Alguno de los proyectos anteriores de Visualizar]]
