#+CATEGORY: proyecto, visualizar, medialab-prado, datalab
#+TAGS: migraciones, refugiadxs, datos abiertos, opendata
#+DESCRIPTION: Taller internacional de visualización de datos Visualizar'17
#+TITLE: Migraciones
#+DATE: <2017-04-26 mié>
#+AUTHOR: Adolfo Antón Bravo
#+EMAIL: adolfo@medialab-prado.es
#+OPTIONS: todo:nil pri:nil tags:nil ^:nil 
#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:nil reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+OPTIONS: toc:nil
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: linear
#+REVEAL_THEME: sky
#+REVEAL_HLEVEL: 2
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal Introduction.">
#+REVEAL_POSTAMBLE: <p> Creado por adolflow. </p>
#+REVEAL_PLUGINS: (highlight markdown notes)
#+REVEAL_EXTRA_CSS: file:///home/flow/Documentos/software/reveal.js/css/reveal.css
#+REVEAL_ROOT: file:///home/flow/Documentos/software/reveal.js/


* Intro

#+BEGIN_QUOTE
#+END_QUOTE

#+BEGIN_QUOTE
http://dle.rae.es/?id=PE38JXc Del lat. migratio, -ōnis.
f. Viaje periódico de las aves, peces u otros animales migratorios.
f. Desplazamiento geográfico de individuos o grupos, generalmente por causas económicas o sociales.
f. Inform. Paso de los programas, archivos y datos de un sistema desde una determinada plataforma tecnológica a otra diferente.
f. Quím. Desplazamiento de una sustancia.
#+END_QUOTE

El programa [[http://medialab-prado.es/visualizar][Visualizar]] de Medialab-Prado celebra su décimo aniversario
con un taller dedicado a las *migraciones*, realizado en colaboración
con [[http://porcausa.org][PorCausa]].

La migración humana es uno de los significados de la palabra [[http://dle.rae.es/?id%3DPE38JXc][migración]]
de la [[http://rae.es/][Real Academia Española de la Lengua]], lo cual nos sitúa en
escenarios muy diversos. No querríamos olvidar la consideración de la
migración humana como un derecho, libertad de movimiento, pero también
como una característica intrínseca a la civilización. Las personas
deciden desplazarse por muchos motivos, a veces forzadas, como es el
caso de quienes buscan refugio, otras veces como fruto de una decisión
personal o familiar. Investigar los flujos migratorios es
imprescindible para entender y defender este derecho.

En 2014 nos interesó un proyecto que se desarrolló en México,
Migrahack –lamentablemente no queda su web original pero
afortunadamente existe archive.org–, donde buscaron dar mayor
visibilidad al tema de inmigración, descifrar las historias que
ocultan los números y unir los datos con la creatividad y la
tecnología para narrar la situación diaria de los migrantes, su
aportación vital, la evolución de la inmigración entre México, Estados
Unidos y Centroamérica y descifrar algunas de las percepciones
erróneas sobre este segmento de la población.

En Visualizar buscamos dar sentido a la compleja realidad, muchas veces filtrada por los datos, a través de visualizaciones. Todas las ediciones pasadas han tomado la ciudad de alguna u otra manera como objeto de estudio, análisis y como territorio a explorar. En este caso nos centramos en una característica, en un proceso, en un comportamiento: el movimiento sobre el territorio mundo. Debemos alertar, también, que en lo que concierne a las personas o grupos, entran en juego la variable distancia y la soberanía nacional. Por ejemplo, se llama desplazadas a las personas que migran en el interior de un país, sin cruzar la frontera, por causa de un conflicto; y también a las que se desplazan por causas climáticas, incluso cruzando fronteras; en otros casos, se puede hablar de turistas, asistentes a congresos, estudiantes Erasmus... Si atendemos a las cuatro acepciones de la palabra migración, se pueden vislumbrar con facilidad distintos proyectos que sobre la misma temática de las *migraciones* toquen distintas perspectivas de la misma:

** Migraciones de la fauna y flora
- Viajes estacionales de aves.
- Moivmientos para disponer de alimentos.
- Cambios en el hábitat, naturales o artificiales, normalmente alteraciones producidas por la acción humana, ya sean infraestructuras temporales o fijas.
- En respuesta a cambios climáticos habituales o como consecuencia del cambio climático.
** Migraciones de personas o grupos
- Migraciones por infraestructuras o a consecuencia del cambio climático.
- Personas retornadas, el proceso migratorio que a veces es de ida y vuelta.
- Migraciones económicas o laborales.
- Personas que buscan refugio por incumplimiento de los derechos humanos.
- Personas que huyen de conflictos.
- Turismo, vacaciones, viajes de placer.
- Viajes científicos, académicos, estudiantes
** Migraciones de datos
- Movimiento de datos en la Web y cualquier otro servicio de Internet
- Privacidad de los datos
- Rastro de personas y sus dispositivos electrónicos, IoT.
- Rastro de cosas, mercancías.
- Migración de datos
- Migración de aplicaciones
- Impactos sociales y culturales

** Migraciones de sustancias
- Migraciones de sustancias en envases y materiales que entran en contacto con alimentos, como los utensilios de cocina y los equipos de procesado de alimentos.
- Migraciones de sustancias nocivas en artículos textiles de uso común, técnicos o especializados.
- Contaminación ambiental.
- Calidad de las aguas y los aires.

* Ejemplos

** Proyectos

- [[http://www.themigrantsfiles.com/][The Migrants' Files]], un consorcio de periodistas de quince países europeos coordinado por [[http://www.jplusplus.org][Journalism++]]
- [[http://www.elconfidencial.com/tags/otros/the-migrants-files-10249/][Participación de El Confidencial en The Migrant's Files]]
- [[https://data.humdata.org/organization/the-migrants-files][Datos de The Migrant's Files en HDX]]
- [[http://www.enciclopedia-de-los-migrantes.eu/es/projet/][La enciclopedia de los migrantes]]
- [[http://elpais.com/agr/3500_millones/a/][3500 millones]], coordinado por Gonzalo Fanjul.

** Artículos

- [[http://elpais.com/elpais/2017/04/20/3500_millones/1492718534_903430.html][La ayuda al desarrollo no frena las migraciones]]
- [[http://www.elmundo.es/papel/firmas/2017/03/06/58bd7c98268e3e687b8b45b5.html][Refugiados]]
- [[https://blog.infotics.es/2013/04/07/adios-al-inmigrante-ilegal-en-associated-press/][Adiós al inmigrante ilegal en Associated Press]]
- [[http://www.bbc.com/mundo/vert-earth-39502506][Las fascinantes pistas que dan los análisis de ADN sobre quiénes fueron los primero habitantes de América]]
- [[http://www.bbc.com/mundo/noticias-internacional-39579498][El drama de los migrantes africanos que son vendido en "mercados de esclavos" en Libia]]
- [[http://www.bbc.com/mundo/internacional/2016/06/160606_naufragio_victimas_catania_africanos_migrantes_all][Relato de uno de los naufragios de migrantes más trágicos en el Mediterráneo]]
- [[http://www.bbc.com/mundo/media-39310125]["Nos tratan como animales": la "inhumana" situación de los migrantes que Hungría quiere encerrar en contenedores]]
- [[http://www.bbc.com/mundo/vert-cap-39572735][Los trabajadores extranjeros que están dejando Reino Unido por el Brexit]]
- [[http://www.bbc.com/mundo/noticias/2015/09/150918_crisis_migratoria_ninos_explotados_lb][Prostituidos y explotados: la dura realidad de los niños migrantes abandonados por Europa]]
- [[http://www.elmundo.es/sociedad/2017/01/29/5888e814468aebf7458b45da.html][Las cartas del desarraigo]]
- [[http://sociedad.elpais.com/internacional/2017/04/05/actualidad/1491405727_917039.html][Del locutorio a WhatsApp: emigrar en tiempos de Internet]]
- [[http://elpais.com/elpais/2016/01/22/ciencia/1453482170_426434.html][Las cigüeñas acortan su migración por la basura y los cultivos humanos]]
- [[http://elpais.com/elpais/2016/03/04/ciencia/1457089717_887650.html][Así es el viaje del insecto que recorre la distancia más larga del mundo]]
- [[http://www.elmundo.es/baleares/2017/04/11/58ec8feee5fdea691c8b462c.html][Los mapas de las aves marinas]]
- [[http://www.bbc.com/mundo/vert-earth-39273283][Cómo la ballena azul llegó a convertirse en el animal más grande de la historia]]
- [[http://sociedad.elpais.com/sociedad/2014/02/19/actualidad/1392837996_788576.html][El riesgo de que los compuestos químicos pasen del envase a la comida]]
- [[Exponen%20la%20relaci%C3%B3n%20entre%20la%20luz%20artificial%20y%20ciertos%20tipos%20de%20c%C3%A1ncer%20][Exponen la relación entre la luz artificial y ciertos tipos de cáncer]]
- [[http://jech.bmj.com/content/early/2014/01/28/jech-2013-202593][Food packaging and migration of food contact materials: will epidemiologists rise to the neotoxic challenge?]]
- [[http://www.elfinanciero.com.mx/opinion/migracion-quimica-a-alimentos.html][Migración química a alimentos]]
- [[http://www.bbc.com/mundo/noticias/2014/02/140220_salud_empaque_peligros_gtg][Unas 4000 sustancias químicas se utilizan en los empaques de comida]]
- [[http://www.consumer.es/seguridad-alimentaria/normativa-legal/2003/02/25/5268.php][Límite a las migraciones en plásticos para alimentos]]

* Fechas
- Anuncio y convocatoria de proyectos: jueves 4 de mayo
- Fecha límite presentación proyectos: 15 junio
- Anuncio proyectos seleccionados: 22 junio
- Convocatoria colaboradorxs: 23 junio

* Visualizar

Visualizar es un taller internacional de prototipado de proyectos de visualización de datos de Medialab-Prado. Este año se cumple el décimo aniversario –que no la décima edición– de este proyecto que pretende "atender a la disciplina de la visualización de datos, un elemento transversal que utiliza el inmenso poder de comunicación de las imágenes para explicar de manera comprensible las relaciones de significado, causa y dependencia que se pueden encontrar entre las grandes masas abstractas de información que generan los procesos científicos y sociales".

Desde 2007, el programa Visualizar de Medialab Prado investiga las implicaciones sociales, culturales y artísticas de la cultura de los datos, y propone metodologías para hacerlos más comprensibles y abrir caminos para la participación y la crítica.

Visualizar parte de la investigación iniciada por José Luis de Vicente en 2007 en torno a las estéticas de la representación de la información en el contexto de diversos festivales y exposiciones:

- Randonee: Un paseo por el paisajismo del Siglo XXI (Exposición dentro de Sónar 2005, Barcelona, CCCB)
- How to Do Things With Data - Cómo hacer cosas con Datos, en OFFF 2006 (Barcelona, CCCB)
- Estética de Datos (Simposio dentro de ArtFutura 2006, Barcelona, Mercat de les Flors).

En las seis ediciones que se han celebrado hasta ahora, el programa /Visualizar/ ha contado con figuras internacionales como Ben Fry, Aaron Koblin, Stamen, Fernanda Viegas, Adam Greenfield, Bestiario, Adrian Holovaty, Sunlight Foundation, Mark Hansen, Manuel Lima, Dietmar Offenhuber, Amber Frid-Jimenez, Andrew Vande Moere, Greg Bloom, Sisi Wei o Yuri Engelhardt, entre otros.
(por desarrollar)

* Movilidad
También nos gustaría resaltar la conveniencia del tema en cuanto está relacionado con otros talleres de Medialab-Prado que estamos desarrollando este año, el taller de producción de periodismo de datos 2017 (tppd17) e Interactivos'17 (interactivos17). Si en el primero abordamos la movilidad en el territorio España y buscamos a través de los datos buenas historias que compongan proyectos periodísticos, en el segundo nos centramos en el territorio ciudad, mientras que en Visualizar'17 el territorio es el mundo.
Alianzas posibles
PorCausa.org
Mugak
ACNUR
SosRacismo
WWF
etc






  
* Quiénes
** Mentorxs
*** Sisi Wei
ProPublica Newsapps developer, desarrolladora de aplicaciones de
noticias en ProPublica.
*** Yuri Engelhardt
[[http://yuriengelhardt.com/][Assistant professor]] and co–coordinator of the multidisciplinary data
visualization curriculum at the University of Amsterdam. 
** Invitadxs
*** Gonzalo Abril
[[http://pendientedemigracion.ucm.es/info/per3/profesores/gabril/][Doctor en Filosofía]], catedrático, profesor emérito en la Facultad de
Ciencias de la Información de la Universidad Complutense de Madrid.
*** Craig Mills
- [[https://twitter.com/craigmmills][@craigmills]]
CEO of Vizzuality: Visualising Good.
*** Javier Pérez
Director de CIECODE
*** Mariano Salvador
Director de la Fundación Zaragoza Ciudad del Conocimiento
*** Sergio Leiva
- [[https://twitter.com/saleiva?lang=es][@saleiva]]
Jefe de producto en Carto.
*** Alberto González

* Agenda
** Simposio: 26-27
*** Inauguración, 2016/09/26
- 9:30-10:00, recepción y café
- 10:00-10:15, presentación de Visualizar'16, por Laura Fernández y
  Adolfo Antón Bravo de Medialab-Prado.
- 10:15-11:15, Visibilidad e invisibilidad, por Gonzalo Abril
  (Universidad Complutense de Madrid).
- 11:30-12:15, [[http://tipiciudadano.es/][TIPI ciudadano]]: Transparencia, información,
  participación, incidencia, por Javier Pérez (CIECODE)
- 12:15-13:00, debate
- 13:00-14:30, comida
- 14:30-15:30, presentación [[http://medialab-prado.es/article/visualizar16-proyectos-seleccionados][proyectos]]
- 15:30-18:00, presentación colaboradores y formación de equipos
- 18:00-18:30, merienda
- 18:30-19:30, Dataviz projects, [[https://www.propublica.org/site/author/sisi_wei][Sisi Wei]]
- 19:30-20:30, networking
*** Segunda sesión, 2016/09/27
- 9:30-10:00, desayuno
- 10:00-13:00, trabajo de equipos
- 13:00-14:30, comida
- 14:30-18:00, trabajo de equipos
- 18:00-18:30, merienda
- 18:30-18:50, [[http://paseoproject.es/][Paseo Project]], por Mariano Salvador (Fundación Zaragoza
  Ciudad del Conocimiento)
- 18:50-19:10, Sergio Leiva (Carto)
- 19:10-19:30, Alberto González (Quadrigram)
- 19:30-19:50, Craig Mills ([[http://www.vizzuality.com/][Vizzuality]]): Visualising
  Good. Visualisations reach every aspect of society, in every corner
  of the world. In his talk Craig Mills, CEO of vizzuality will discuss how
they are using data visualisation to shape people's perceptions of the
planet. Dedicated to solving issues related to climate change,
inequality, nutrition and transparent governments, Craig will show you
how the White House prepares their counties for climate change, Kenyan
farmers change the way they grow crops to save water, Swaziland health
workers reduce malaria and how millions of people are monitoring every
forest on the planet, all with the help of data visualisation. He'll
also look at what is missing in the space of data visualisation and
social good, and what vizzuality are trying to do to solve it. The
talk will be dressed with some of the best interactive visualisations
on the web, please come along and enjoy!
- 19:50-20:30, debate y networking

** Sesiones de trabajo en equipo: 28/9-3/10
Esquema de los días 28 septiembre-3 de octubre, incluidos:

- 9:30-10:00, desayuno			
- 10:00-13:00, trabajo			
- 13:00-14:30, comida			
- 14:30-18:00, trabajo			
- 18:00-18:30, merienda			
- 18:30-20:30, talleres/libre

El día 28 comenzarán las sesiones críticas, ronda de entrevistas con
los equipos para analizar el esquema de trabajo planteado y realizar
propuestas sobre el mismo.

** Charlas/talleres 28/9-3/10
 - 2016/10/01, 18:30-20:30, Charla de Visualización de datos, Ignasi
   Alcalde (ODI Barcelona) 
 - 2016/10/02, 18:30-20:30, Charla de datos abiertos, vocabularios y
   ontologías, María Poveda (OEG-UPM y ODI-Madrid).
 - 2016/10/03, 18:30-20:30, Taller de Carto, Ramiro Aznar (Carto)
 - Standard and Open Data for Social and Community Services, Open
   Referral, Greg Bloom.
 - Los datos cartográficos como motores de los datos abiertos,
   Alejandro Zappala (Adappgeo)
 - Usabilidad de las aplicaciones de datos, Daniel Vila (OEG-UPM)

** 4 de octubre
Dia de finalización de proyectos.

Además, se celebra en Medialab-Prado el /DDJ Action Day/, de
periodismo de datos, en colaboración con [[http://schoolofdata.org][School of Data]], en Alameda0 y
las Salas A y B, por lo que podremos trabajar en la finalización de los proyectos y/o
disfrutar de los talleres o sesiones.

** 5 de octubre

Presentación pública de los proyectos desarrollados. Contaremos con 7
minutos cada proyecto en dinámica Petcha Kucha

Este día celebramos en Medialab el tercer evento previo oficial de
IODC16, la cumbre de las ciudades abiertas o [[http://opencitiessummit.org][Madrid Open Cities Summit
2016]]. Qué mejor evento que éste para realizar la presentación
pública. Disponemos de una hora para los 8 proyectos.						
