#+BLOG: blog.datalab.es
#+CATEGORY: 
#+TAGS: 
#+DESCRIPTION: Notas sobre Visualizar
#+AUTHOR: Adolfo Antón Bravo
#+EMAIL: adolfo@medialab-prado.es
#+TITLE: Visualizar'17: Migraciones
#+DATE: <2017-04-06 jue 10:00>
#+OPTIONS:  num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil toc:nil
#+LATEX_HEADER: \usepackage[english]{babel}
#+LATEX_HEADER: \addto\captionsenglish{\renewcommand{\contentsname}{{\'I}ndice}}
#+LATEX_HEADER: \renewcommand{\contentsname}{Índice}
<<<<<<< HEAD

*Visualizar* es un taller internacional de prototipado de proyectos de
*visualización de datos*. Cumplimos diez años con una edición dedicada
a las *migraciones*.

Estos son los diez proyectos seleccionados:



* Se cultivan allá, se consumen aquí: la travesía de los alimentos hacia tu despensa
- Promotora: Flora Fosset
- Git: https://github.com/medialab-prado/journey-of-food

Desde hace décadas, los habitantes de centros urbanos se desconectaron
del mundo agrícola y del ritmo natural de la tierra.

Hay dos maneras de tener todo tipo de fruta y verdura todo el año:
importando o cultivando en invernaderos climatizados. Los dos métodos
generan gases de efecto invernadero, destrozando cada vez más el medio
ambiente.

Es necesaria una herramienta que permita saber qué comer de cultivo
local y de temporada. Este proyecto tiene por objetivo elaborar una
aplicación que permita saber con precisión qué frutas y verduras se
están cosechando en cada región de España según la época y el tipo de
cultivo. Así aportamos una herramienta para quien quiera consumir
responsablemente, limitando el transporte excesivo de alimentos y el
cultivo en invernaderos climatizados.

* Agrega.la
- Promotor: Adriano Belisario
- Git: https://github.com/medialab-prado/agregala
Agrega.la es una red presente en Brasil, Argentina, Colombia y México,
que tiene como objetivo promover la visibilización de contenidos y
acciones entre medios independientes, libres o comunitarios.

Su plataforma constantemente hace copias de los posts publicados en
Facebook, Twitter o RSS para tener un acceso público y universal al
contenido que de otra manera permanece cautivo.

De esta forma se pretende visualizar y fortalecer la labor de los
colectivos y medios que trabajan de forma autogestionada e
independiente para producir su propia información, la cual no tiene la
misma difusión e impacto que la de los medios masivos o tradicionales
de su ciudad o territorio, y que utilizan los medios de una empresa
privada.

* Trackula
- Promotorxs: Santiago Saavedra López y Sofía Prosper Díaz-Mor
- Git: https://github.com/medialab-prado/trackula

Trackula consiste en una forma de poder visualizar cómo distintos
entes pueden rastrear tus migraciones por la web, de forma
inadvertida, y visualizar las relaciones entre ellos, y cuánta
información de ti pueden estar disponiendo.

Se plantea como una infografía interactiva en forma de web sobre el
historial individual, personalizada con los datos del navegador de
cada uno, de forma que uno pueda ver, en su realidad, qué información
está decidiendo otorgar a terceros al navegar por Internet.

El carácter individual la convierte en una experiencia muy personal,
siendo el impacto producido diferente en cada caso, y relacionado con
la experiencia de cada uno con la web.

* Lxs menores refugiadoxs de la guerra de Siria
- Promotorxs: Ferrán Morales Jacas, Ignasi Alcalde y Amanda Figueras.
- Git: https://github.com/medialab-prado/menoresRefugiadxs

Con los datos de migraciones del Informe *THE GROWING CRISIS FOR
REFUGEE AND MIGRANT CHILDREN* de /Unicef/, realizaremos un proyecto de
visualización sobre el impacto de la migración de los niños y niñas de
Siria, desde el inicio de la guerra en 2010 hasta los datos más
actuales que se dispongan.

270.000 menores de edad, refugiadxs, llegaron a Europa
durante el año 2015, de lxs cuales más de 26.000 estaban solos, sin familia y sin
ninguna persona adulta que cuidara de ellxs, según los datos de /Save
the Children/ y Unicef. De estxs, 10.000 niños se encuentran
actualmente desaparecidxs según la Europol.

Nuestro proyecto de visualización constará de diferentes capítulos, de
los cuales los primeros servirán para contextualizar la situación
actual de Siria, para llegar a lxs niñxs desaparecidxs.


* Mobilomics
- Promotor: David Pastor
- Git: https://github.com/medialab-prado/mobilomics

Este proyecto trata de desarrollar una plataforma para visualizar
patrones y perfiles asociados a distintos objetivos: eventos,
localizaciones geográficas o grupos de población específicos. Resulta
crítico para abordar fenómenos como las migraciones por alguna de sus
causas.

Pretende ofrecer una adecuada visualización de la movilidad y las
migraciones que se pueda adaptar a grupos de población específica y
grupos de interés según el ámbito de estudio relacionado.

La capacidad de geolocalizar de las plataformas de visualización no
sirve a la hora ofrecer datos desagregados según el grupo de población
de interés en cada caso.

Se deben explotar además otras fuentes de datos como las redes
sociales, datos de telefonía móvil o sensores de geolocalización para
entender la movilidad y las migraciones.


* Cerebros en movimiento
- Promotorxs: Clara Lima Romero, Michele Catanzaro y Elisa Vivas, de /El
Periódico de Catalunya/.
- Git: https://github.com/medialab-prado/cerebrosEnMovimiento

** Nombre corto
cerebros
** Texto
Entre lxs científicxs está difundida la percepción que la crisis y los
recortes han abierto un boquete en la ciencia de los países afectados
por el cual ha salido mucho talento que han recibido otros. También
cuestiones como el Brexit pueden afectar a estas migraciones.

Sin embargo, no existen datos conclusivos que lo confirmen. Aprovechando
este vacío, algunos gobiernos (como el español) argumentan que no hubo
fuga de cerebros, sino un normal patrón de movilidad, con cesión y
adquisición de talento en iguales proporciones.

¿Cómo abordar este asunto con certeza? A través de una base de datos
de currículos de científicxs, repositorio que acumulan millones de
perfiles y permiten detectar los cambios de país emprendidos por un
determinado investigador, a medida que su afiliación cambia en el
tiempo.


* Población dirigida: el caso de lxs colonxs de la España verde de Franco
- Promotorxs: Territorio de datos
- Git: https://github.com/medialab-prado/poblacion-dirigida

Entre los años 1939 y 1973, el Instituto Nacional de Colonización
promovió la construcción en España de más de 300 pueblos. El ambicioso
plan que tenía como objetivo la creación de amplias zonas de regadío y
el aumento de su productividad movilizó aproximadamente a 55.000
familias.

Este hecho supuso el movimiento migratorio de mayor envergadura
promovido por el Estado español en el siglo XX. La colonización fue un
proceso multidimensional caracterizado por una toma abundante de
datos. Acceder a estos es por tanto acceder a la memoria de una
transformación. La historia de un conjunto de mundos creados de la
nada, contada desde la consulta y visualización continua de datos
históricos de archivos y estudios legitimados.

Ventanas de datos, en definitiva, a un territorio cuya escala y
memoria cambiaron para siempre.

* Planeta excedencia
- Promotora: [[https://twitter.com/m_llop][María Llop]]
- Git: https://github.com/medialab-prado/planeta-excedencia

En España, hay hombres y mujeres que cuando son padres deciden migrar
al planeta de la excedencia por cuidado de hijxs. En ocasiones, es una
migración sin retorno al mundo laboral.

Este proyecto quiere visualizar esta realidad y profundizar en ella
para analizar cuánto de voluntaria es esta opción como posible forma
de conciliación entre la vida laboral y la familiar.

Para ello preguntaremos a los escasos datos disponibles y diseñaremos
una encuesta que nos dé pistas sobre la información que desconocemos.



=======
#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:nil reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: linear
#+REVEAL_THEME: sky
#+REVEAL_HLEVEL: 2
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Herramientas de Scraping de PDF y Web.">
#+REVEAL_POSTAMBLE: <p> Creado por adolflow. </p>
#+REVEAL_PLUGINS: (highlight notes)
#+REVEAL_EXTRA_CSS: file:///home/flow/Documentos/software/reveal.js/css/reveal.css
#+REVEAL_ROOT: file:///home/flow/Documentos/software/reveal.js/

*Visualizar* es un taller internacional de prototipado de proyectos de
*visualización de datos*. En [[http://s.coop/visualizar17][Visualizar'17: Migraciones]] se cumple el
**décimo aniversario* --que no la décima edición-- de este proyecto
*que pretende "atender a la disciplina de la visualización de datos,
*un elemento transversal que utiliza el inmenso poder de comunicación
*de las imágenes para explicar de manera comprensible las relaciones
*de significado, causa y dependencia que se pueden encontrar entre las
*grandes masas abstractas de información que generan los procesos
*científicos y sociales".

* Visualizar

Desde 2007, el programa [[http://medialab-prado.es/visualizar][Visualizar]] de [[http://medialab-prado.es][Medialab-Prado]] investiga las
implicaciones sociales, culturales y artísticas de la cultura de los
datos, y propone metodologías para hacerlos más comprensibles y abrir
caminos para la participación y la crítica.

Visualizar parte de la investigación iniciada por *José Luis de Vicente* en 2007 en torno a las estéticas de la representación de la información en el contexto de diversos festivales y exposiciones:
- /Randonee: Un paseo por el paisajismo del Siglo XXI/ (Exposición dentro de Sónar 2005, Barcelona, CCCB)
- /How to Do Things With Data - Cómo hacer cosas con Datos/, en OFFF
  2006 (Barcelona, CCCB)
- /Estética de Datos/ (Simposio dentro de ArtFutura 2006, Barcelona, Mercat de les Flors).

En las seis ediciones que se han celebrado hasta ahora, el programa
Visualizar ha contado con figuras internacionales como Ben Fry, Aaron
Koblin, Stamen, Fernanda Viegas, Adam Greenfield, Bestiario, Adrian
Holovaty, Sunlight Foundation, Mark Hansen, Manuel Lima, Dietmar
Offenhuber, Amber Frid-Jimenez, Andrew Vande Moere, Greg Bloom, Sisi
Wei o Yuri Engelhardt, entre otros.


* Migraciones

Qué nos dice la [[http://rae.es/][Real Academia Española de la Lengua]]:

#+BEGIN_QUOTE
http://dle.rae.es/?id=PE38JXc
Del lat. migratio, -ōnis.

1. f. Viaje periódico de las aves, peces u otros animales migratorios.

2. f. Desplazamiento geográfico de individuos o grupos, generalmente por causas económicas o sociales.

3. f. Inform. Paso de los programas, archivos y datos de un sistema desde una determinada plataforma tecnológica a otra diferente.

4. f. Quím. Desplazamiento de una sustancia.
#+END_QUOTE

El tema de las migraciones es absolutamente de actualidad y lo seguirá
siendo, sobre todo en su versión más dramática y extrema de lxs
refugiadxs de conflictos provocados, alentados, observados o tolerados
por las potencias occidentales.

En 2014 nos interesó un proyecto que se desarrolló en México,
*Migrahack* --lamentablemente no queda su web original pero
afortunadamente existe [[https://web-beta.archive.org/web/20150317032615/http://justicejournalism.org/es/events/ciudad-de-mexico-mexico-2014][archive.org]]--, donde buscaron dar mayor
visibilidad al tema de inmigración, descifrar las historias que
ocultan los números y unir los datos con la creatividad y la
tecnología para narrar la situación diaria de los migrantes, su
aportación vital, la evolución de la inmigración entre México, Estados
Unidos y Centro América y descifrar algunas de las percepciones
erróneas sobre este segmento de la población.

En Visualizar buscamos dar sentido a la compleja realidad, muchas
veces filtrada por los datos, a través de visualizaciones. Todas las
ediciones pasadas han tomado la ciudad de alguna u otra manera como
objeto de estudio, análisis y como territorio a explorar. En este caso
nos centramos en una característica, en un proceso, en un
comportamiento: el movimiento. Si atendemos a las cuatro acepciones de
la palabra /migración/, se pueden vislumbrar con facilidad distintos
proyectos que sobre la misma temática toquen distintas perspectivas de
la misma, con subgrupos a su vez:

** Migraciones de la fauna y flora.
 - Ciclo de la vida
 - Alteraciones producidas por la mano de la humanidad.
 - Y más específicamente por el cambio climático.

** Migraciones de personas o grupos.
 - Migraciones económicas o laborales.
 - Personas que buscan refugio por incumplimiento de los derechos humanos.
 - Personas que huyen de las guerras.
 - Turismo, vacaciones, viajes de placer
 - Viajes científicos, académicos, estudiantes

** Migraciones de datos.
 - Movimiento de datos en la Web y cualquier otro servicio de Internet
 - Privacidad de los datos
 - Rastro de personas
 - Rastro de cosas
 - Migración de datos
 - Migración de aplicaciones

** Migraciones de sustancias (física y química).
 - La vida es migrante
 - (por desarrollar)

* Movilidad

También nos gustaría resaltar la conveniencia del tema en cuanto está relacionado con otros talleres de Medialab-Prado que estamos desarrollando este año, el [[http://medialab-prado.es/article/v-taller-de-produccion-de-periodismo-de-datos-la-espana-vacia][taller de producción de periodismo de datos 2017]] (tppd17) e [[http://medialab-prado.es/article/interactivos17][Interactivos'17]] (interactivos17). Si en el primero abordamos la movilidad en el territorio *España* y buscamos a través de los datos buenas historias que compongan proyectos periodísticos, en el segundo nos centramos en el territorio *ciudad*, mientras que en Visualizar'17 el territorio es el *mundo*.

* Alianza con PorCausa.org

Cuando pensamos en aliadxs para este taller inmediatamente pensamos en [[http://porcausa.org][Porcausa.org]]. Fundado por:

- Sindo Lafuente (Elpais.com, Elmundo.es, Soitu.com, maestro en la Fundación Gabriel García Márquez)
- Gonzalo Fanjul (director en ISGlobal, autor del blog de El Pais /3.500 millones/)

PorCausa se define como una organización que quiere lugar contra la mentira informativa a través de la información que salva vidas. Por información se refiere a trabajo de investigación y periodismo en temas sociales como la desigualdad, la pobreza o la *migración*, contenidos de calidad sin enfoques sesgados o dañinos, sin mentira, sin manipulación.

Trabajan con periodistas de los principales medios de España y Latinoamérica para difundir sus enfoques a través de los grandes medios, pero también con:

- /Think tanks/ de desarrollo del mundo como [[https://www.odi.org/][Overseas Development Institute]] (centrado en desarrollo internacional y humanitario) o [[https://www.cgdev.org/][Center for Global Development]] (centrado en desarrollo internacional)
- Universidades como la Rey Juan Carlos, la Carlos III, Autónoma de Madrid, Pontificia de Comillas, Harvard, Standford, Columbia
- Con los principales medios y periodistas de nuestro país, como El País, Público, eldiario.es, Cadena Ser, El Intermedio, etc.

Además, en su patronato cuentan con:
- Soledad Gallego Díaz
- Iñaki Gabilondo
- Carlos Martínez de la Serna, fundador de PorCausa.org y actualmente en Univisión EE.UU.
- Giannina Segnini, fundadora de la Unidad de Datos de /La Nación/ de Costa Rica y actualmente profesora en la Universidad de Columbia, Nueva York.
- Rosental Calmon Alves, Centro Knight para el Periodismo en las Américas, profesor de periodismo en la Universidad de Texas en Austin, Cátedra Knight de Periodismo y Cátedra UNESCO de Comunicación
- Kevin Watkins, director ejecutivo del Overseas Development Institute
- José Juan Toharia, fundador y presidente de Metroscopia, Catedrático de Sociología en la Universidad Autónoma de Madrid, primer director de la Escuela de Periodismo UAM-El País y miembro fundador de Cuadernos para el Diálogo.
>>>>>>> master
