#+CATEGORY: proyecto, curro, medialab-prado
#+TAGS: transparencia, participación ciudadana, open data, datos abiertos
#+DESCRIPTION: Agenda del proyecto de Transparencia y participación ciudadana de Medialab-Prado
#+TITLE: Visualizar'17: Migraciones, convocatoria de colaboradorxs
#+DATE: <2017-04-27 jue>
#+AUTHOR: Adolfo Antón Bravo
#+EMAIL: adolfo@medialab-prado.es
#+OPTIONS: todo:nil pri:nil tags:nil ^:nil 

#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:nil reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+OPTIONS: toc:nil
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: linear
#+REVEAL_THEME: sky
#+REVEAL_HLEVEL: 2
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal Introduction.">
#+REVEAL_POSTAMBLE: <p> Creado por adolflow. </p>
#+REVEAL_PLUGINS: (highlight markdown notes)
#+REVEAL_EXTRA_CSS: file:///home/flow/Documentos/software/reveal.js/css/reveal.css
#+REVEAL_ROOT: file:///home/flow/Documentos/software/reveal.js/

Call to collaborate on any of the [[http://medialab-prado.es/article/visualizar17-migraciones-proyectos-seleccionados][8 projects selected]] for the
International workshop on data visualization [[http://medialab-prado.es/article/visualizar17-migraciones][Visualizar'17: Migraciones]]
that is celebrated *from 15 to 30 of September*.

#+CAPTION: Visualizar17: Migraciones, 15-30 September in collab with PorCausa.org, CC BY NC 2.0
#+ATTR_HTML: :alt Visualizar17: Migraciones. 15-30 September in collab with PorCausa.org, CC BY NC 2.0 :title v17
http://medialab-prado.es/mmedia/20/20392/500_0.png

Registration is free and ends one week before the start
Of the workshop, *September 7th*.

Medialab-Prado offers free accommodation for collaborators who need it
during the workshop (lLimited places on request and in order of
registration, up to *1 July*).

* About this call
Medialab-Prado publishes this call for all those who
Want to participate in the workshop [[http://medialab-prado.es/article/visualizar17-migraciones][Visualizar17: Migraciones]], as
collaborator in one of the working groups that will develop the
[[http://medialab-prado.es/article/visualizar17-migraciones-proyectos-seleccionados][selected proposals]].

The figure of the collaborator is fundamental in the approach and
development of the Medialab-Prado workshops, as these are conceived
such as collaborative workspaces, the exchange of knowledge and
theoretical-practical training, in an environment of horizontal
relationship among all workshop participants, whether mentors, tutors,
developers or the collaborators themselves.

Collaborators can be part of the development team of one or more of
the proposals selected according to their interests, contributing with
their knowledge and ideas while learning from the rest of the group
and workshop tutors.

However, we suggest to collaborators to focus on a single project to
ensure greater commitment to it during the all phases of the workshop.

As specified in the terms of the call, the names of the collaborators
will appear in the credits of the draft. In addition, Medialab-Prado
will deliver a supporting document of the participation in the
workshop to those collaborators who request

The workshop will be held *from 15 to 30 September* in
schedule from 10:00 a.m. to 6:30 p.m., with a break to eat. Occasionally
there will be small workshops, presentations or parcours between 18:30 and
20:30.

If you are interested, fill in and send the FORM you will find below

If you have any questions, you can check the FAQ or
Write to visualizar (at) medialab-prado.es.
* Assignment of place in the workshop

There is no selection process for collaborators so all registrations
received will be accepted until completion seating

Once the form has been sent, you will receive an email confirming that your data has been
Which means that you have your place. Confirmation does not directly imply that you have a place in the
accommodation provided by the workshop.

* Accommodation

For residents outside Madrid, Medialab-Prado will cover a limited
number of places during the days of the workshop. The assignment will
be made by strict order of application, for what the registration as a
collaborator does not automatically guarantee obtaining a place.

Do not forget to check in the form the dates of entry and exit if
You choose this option. The maximum stay dates will be check-in
2017-09-14 and check-out 2016-09-30.

Medialab-Prado will reach you to confirm the reservation of your
accommodation.

The deadline for requesting a place is *July 1st*.

Medialab-Prado does not cover travel and subsistence expenses.
* Medialab-Prado online community

The teams will be set up through the platform
[[Https://github.com/visualizar17][Github]], where the selected projects will be published. You will be
subscribed to a mailing list and invited to a Telegram group.

* Instructions for completing the form

In the field of "Comments" you must indicate:
- Your availability to participate actively and presently in the workshop. The highest degree of dedication is recommended since it is an intensive workshop.
- Title of at least two projects in which you would like to participate, if known.
- Anything else.
* Dudas

Do not esitate to drop us an email to medialab-prado.es if you have
any doubt.


