#+TITLE: Visualizar17: Migraciones, projects selected
#+AUTHOR: Adolfo Antón Bravo
#+DATE: <2017-06-27 mar>
#+EMAIL: adolfo@medialab-prado.es
#+LANGUAGE: es
#+OPTIONS: skip:nil ^:nil author:nil timestamp:nil num:nil TeX:nil
#+DESCRIPTION: Listado de proyectos seleccionados para Visualizar17: Migraciones, a desarrollar del 15 al 30 de septiembre junto con lxs colaboradorxs
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER: colorlinks,%
#+LATEX_HEADER: citecolor=Violet,%
#+LATEX_HEADER: linkcolor=blue,%
#+LATEX_HEADER: urlcolor=blue
#+LATEX_HEADER: }

We present the eight projects selected from the [[http://medialab-prado.es/article/visualizar17-migraciones-convocatoria-de-proyectos][call for proposals]]
for [[http://medialab-prado.es/article/visualizar17-migraciones][Visualizar17: Migrations]], international workshop on
data visualization carried out in collaboration with
[[https://porcausa.org/][PorCausa.org]]. Please apply for the [[http://medialab-prado.es/article/visualizar17-migraciones-convocatoria-de-proyectos][Call for Collaborators]]!

#+CAPTION: Visualizar17: Migraciones, 15-30 September in collab with PorCausa.org, CC BY NC 2.0
#+ATTR_HTML: :alt Visualizar17: Migraciones. 15-30 September in collab with PorCausa.org, CC BY NC 2.0 :title v17
http://medialab-prado.es/mmedia/20/20392/500_0.png

We remind you that the workshop takes place from *September 15 to 30 
of 2017* and that in order to participate you must register for the
[[http://medialab-prado.es/article/visualizar17-migraciones-convocatoria-de-colaboradorxs][Call for Collaborators]] which remains open from *June 27th to
September 7th*

The 8 projects will have the support and advice of the
[[http://medialab-prado.es/article/visualizar17-migraciones#org65fba37][Visualizar17 team]].

* The journey of food to your pantry (/Se cultivan allá, se consumen aquí: la travesía de alimentos hacia tu despensa/.)
De *Flora Fosset*

It's been decades that citizens of urban centers disconnected from the
agricultural world and the natural rhythm of plants

We have to be aware that foreign products and out of season products
have a massive carbon footprint. We have to get rid of this habit of
eating anything anytime and go back to consume food like our
grandparents used to do: following mother nature’s rhythm.

We need a tool that shows what can be eaten from local farming and
in-season. This project’s goal is to elaborate an app that allows
knowing what are the fruits and vegetables than are being harvested in
every region of Spain, depending on the season and the type of
culture. That way, we’ll offer a tool for the ones who want to eat
responsibly, limiting the excessive transport of food and the farming
in heated greenhouses.

* Agrega.la
By /Adriano Belisario/

Agrega.la is a network working in Brazil, Argentina, Colombia and
Mexico. It aims to promote the visibility of contents and actions
between independent, free or communitary media.

This platform constantly copy posts published in Facebook, Twitter or
RSS to gather their contents in a common, free and open space.

This is intended to visualize and strengthen the work of the groups
and projects that work in a self-managed way and to produce their own
information, which does not have the same diffusion and impact as the
mass media of their city or territory, and for those who use the media
which belong to private companies.

* Trackula
De /Santiago Saavedra López y Sofía Prosper Díaz-Mor/

Trackula consists in a tool capable of visualizing how different
entities can inadvertently track your migrations on the web and feel
the relationships between these entities, and how much aggregated
information on you may be available to them from your usage patterns.

Initially proposed as an interactive infographic website, taking
information from the browser history, so that the user can see which
information they are giving to third-parties when browsing places on
the Internet.

Wildly different impacts are to be expected as browsing the Internet
is a unique experience for everyone, as is the information anyone
gives away.

* Children refugees from the war of Syria (/Los menores refugiados de la guerra en Siria/
de /Ferrán Morales Jacas/

With the migration data from the report *THE GROWING CRISIS FOR
REFUGEE AND MIGRANT CHILDREN* from /Unicef/, we will carry out a
visualization project on the impact of the migration of the children
of Syria from the start of the war in 2010 to the most current data
available

70,000 children, refugees, arrived in Europe during the year 2015, of
which more than 26,000 were alone, without family and without no adult
person who cares for them, according to the data of /Save The
Children/ and /Unicef/. 10,000 of them are Currently disappeared
according to Europol.

Our visualization project will consist of different chapters, from the
contextualization of the conflict to the aim of reaching missing
children.

* Mobilomics
By /David Pastor/

This project aims at developing a visualization platform to visualize
mobility patterns and profiles associated to different targets:
events, geographical locations or specific population groups. It is critical to
understand these concepts in order to tackle migrations and its
causes.

A proper visualization of mobility and migrations has to be adapted to
specific population groups and targets of interest for
studies.

Geolocation intelligence visualization platforms fail to
provide a disaggregation of population groups that might be of
interest.

A specific visualization platform is therefore required to exploit big
data sources such as social networks, mobile phone data or geolocation
sensors to understand mobility and migrations.

* Brain Drain (/cerebros en movimiento/)
By /Clara Lima Romero/, /Michele Catanzaro/ y /Elisa Vivas/, from /El
Periódico de Catalunya/.

Among scientists, there is a widespread perception that the crisis and
the subsequent budget cuts have opened a wound in the science of the
affected country, through which a lot of scientific talent has flowed
away. Secondary shocks as for instance the Brexit, may have an effect on
this migrations as well.

However, there are no conclusive data that confirm it. Taking
advantage of this information gap, some governments (like the Spanish
one) argue that there was no brain drain, but rather a normal pattern
of mobility, with attraction and loss of talent in equal proportions.

How can we tackle this topic? Through a dataset
that has been almost unexplored until now which offers an unusual possibility
to throw light on this issue, the large dataset
of scientists CVs. This repositories, in which millions of
profiles are accumulated, allow to detect counties changes of each
single researcher, as reflected by the affiliations' changes.



* Controlled population: the case of settlers in the Green Spain of Franco (/Población dirigida: el caso de los colonos de la España verde de Franco/)
De /Carmen Pellicer Balsalobre/

Between 1939 and 1973, the National Institute of Colonization (INC)
promoted the construction in Spain of more than 300 villages. The
ambitious plan that aimed to create large irrigated areas and increase
its productivity mobilized approximately 55,000 families.

This fact was the most important migratory movement promoted by the
Spanish State in the twentieth century.

Colonization was a multidimensional process characterized by a big
data collection. Accessing this data is accessing the memory of a
transformation. This is the story of a set of worlds created from
scratch, narrated from the consultation and continuous visualization
of historical data of archives and legitimate studies.

Data windows, in short, to a territory which scale and memory changed
forever.

* Planet Leave (/Planeta excedencia/)
By /María Llop/

In Spain, there are men and women who, when they are parents, decide
to migrate to the /exceedance planet/ by babies care. Sometimes it is
a migration without return to the world of work.

This project wants to visualize this reality and go deeper into it
to analyze how voluntary this option is as a possible way
of reconciliation between work and family life.

We will ask for the limited data available and design a survey that
gives us clues about the information we do not know.

